name: tableau_langchain
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12.2
    - pip=23.3.1
    - conda-forge::notebook=7.3.3
    - conda-forge::nb_conda_kernels=2.5.1
    - ipykernel=6.29.5
    - python-dotenv=1.1.0
    - pyjwt=2.10.1
    - langchain=0.3.21
    - langsmith=0.2.11
    - pip:
        - langgraph==0.3.21
        - langgraph-cli==0.1.81
        - langchain-anthropic==0.3.10
        - langchain-openai==0.3.11
        - langchain-pinecone==0.2.3
        - langchain-tableau==0.4.35
        - langchain-community==0.3.20
        - llama-index==0.12.27
        - llama-index-vector-stores-pinecone==0.4.5
        - "pinecone-client[grpc]==6.0.0"
        - tavily-python==0.5.3
